### ISSUE TITLE
Unable to list all Namespaces 

### ISSUE THREAD

**Issue by nikhilgorantla** [ameerthehacker/kubelive#40] opened 2020-07-19 20:05 UTC
**Describe the bug**
When we have more than 100 namespaces, Kubelive cannot list all the namespaces defaults to last namespaces.

**To Reproduce**
MACHINE         :- MacBook Pro 
NPM                 :- NPM install from brew {brew install npm}
KUBELIVE        :- Installed kubeve live from npm (npm install -g kubelive) 

1. kubelive --version -- 1.5.0
<img width="252" alt="image" src="https://user-images.githubusercontent.com/35358177/87883983-212e7380-c9d9-11ea-8d1f-8eb05d0eb697.png">

2. kubelive get pods
<img width="747" alt="image" src="https://user-images.githubusercontent.com/35358177/87884043-7e2a2980-c9d9-11ea-9fcf-6f771306a2cf.png">

**Comment by ameerthehacker** [comment] 2020-07-20 05:09
This is duplicate of #13 so will close this, please have eye on the other issue

**Closed by ameerthehacker** 2020-07-20 05:09 UTC
